layout_spectrum: 1
typography_spectrum: 0.4247312
color:
  saturation: 0.1043518
  lightness: 0.5394265
  brandStrength: 0.4766917
  brandColors:
    - '#030316'
    - '#FBFCFB'
    - '#65656E'
    - '#024C77'
    - '#6D6602'
  rhythmicContrast: 0.5107527
name: Designer Consigner
