name: Designer Consigner
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4247312
title: Designer Consigner By Sarah Taylor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030316'
    - '#FBFCFB'
    - '#65656E'
    - '#024C77'
    - '#6D6602'
  brandStrength: 0.4766917
  lightness: 0.5394265
  saturation: 0.1043518
  rhythmicContrast: 0.5107527
purpose: []
